<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0-windows7.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
	<GenerateAssemblyInfo>false</GenerateAssemblyInfo>
	<IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Castle.Core" Version="5.2.1" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.14.1" />
    <PackageReference Include="Moq" Version="4.20.72" />
    <PackageReference Include="NUnit" Version="4.4.0" />
    <PackageReference Include="NUnit3TestAdapter" Version="5.1.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\DataAccess\DataAccess.csproj" />
    <ProjectReference Include="..\FieldVisualizer\FieldVisualizer.csproj" />
    <ProjectReference Include="..\StructureHelperCommon\StructureHelperCommon.csproj" />
    <ProjectReference Include="..\StructureHelperLogics\StructureHelperLogics.csproj" />
    <ProjectReference Include="..\StructureHelper\StructureHelper.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Reference Include="LoaderCalculator">
      <HintPath>..\StructureHelper\Libraries\LoaderCalculator.dll</HintPath>
    </Reference>
  </ItemGroup>

  <ItemGroup>
    <Folder Include="FunctionalTests\Ndms\SteelSections\" />
    <Folder Include="FunctionalTests\RCs\Anchorage\" />
    <Folder Include="UnitTests\ConvertStrategiesTest\" />
    <Folder Include="UnitTests\WindowTests\Calculations\CalculationProperties\" />
  </ItemGroup>

</Project>