<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0-windows7.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Newtonsoft.Json" Version="13.0.4" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\StructureHelperCommon\StructureHelperCommon.csproj" />
    <ProjectReference Include="..\StructureHelperLogics\StructureHelperLogics.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Reference Include="LoaderCalculator">
      <HintPath>..\StructureHelper\Libraries\LoaderCalculator.dll</HintPath>
    </Reference>
  </ItemGroup>

</Project>
