using StructureHelperCommon.Models.FeaMaterials.ExportLogics;

namespace StructureHelperCommon.Models.FeaMaterials
{
    public class ModelBlock : IModelBlock
    {
        private const string forceFactor = "forceFactor";
        private const string lengthFactor = "lengthFactor";
        private const string stressFactor = "stressFactor";
        private const double forceFactorValue = 1.0;
        private const double lengthFactorValue = 1000.0;
        private readonly string modelName;

        public ModelBlock(string modelName)
        {
            ModelName = modelName;
        }

        public string ModelVariableName { get; set; } = "modelName";
        public IAbaqusContext Context { get; private set; }
        public string ModelName { get; set; } = "New model";
        public bool AddImport { get; set; } = false;

        public void Build(IAbaqusContext context)
        {
            Context = context;

            context.Set(new ModelContext
            {
                ModelName = ModelName,
                ModelVaribleName = ModelVariableName,
                ForceFactorName = forceFactor,
                LengthFactorName = lengthFactor,
                StressFactorName = stressFactor,
            });

            var builder = context.Builder;
            builder.AddCommentedHeader("Script generated by StructureHelper");
            builder.AddComment("To run script, select /File->Run Script/ in Abaqus");
            builder.AddComment("All rights to Abaqus software belong to their respective owners, who are not affiliated with the creators of StructureHelper");
            if (AddImport == true)
            {
                builder.AddRaw();
                builder.AddKeyword("from abaqus import *");
                builder.AddKeyword("from abaqusConstants import *");
                builder.AddKeyword("import regionToolset");
                builder.AddKeyword("import mesh");
            }

            builder.AddRaw();
            builder.AddCommentedHeader("Model");
            builder.AddComment("Important! This part of script deletes your existing model with same name!");
            builder.AddComment("If you don't need to create a new model, comment or delete lines as below");
            builder.AddKeyword($"modelName = '{ModelName}' #Change to your model name if you need");
            builder.AddKeyword($"if modelName in mdb.models:\r\n   del mdb.models[modelName]");
            builder.AddKeyword($"mdb.Model(name=modelName)");
            builder.AddKeyword($"{ModelVariableName} = mdb.models[modelName]");
            builder.AddRaw("");
            builder.AddCommentedHeader("Unit factors");
            builder.AddComment("By default, this script uses units of Newtons and millimeters");
            builder.AddComment("If you want to use units of SI, set 1.0 for SI unit");
            builder.AddKeyword($"{forceFactor} = {forceFactorValue} #Unit of force, N");
            builder.AddKeyword($"{lengthFactor} = {lengthFactorValue} #Unit of length, mm in m");
            builder.AddKeyword($"{stressFactor} = {forceFactor} / ({lengthFactor} * {lengthFactor}) # = {forceFactorValue} / ({lengthFactorValue} * {lengthFactorValue}) = {forceFactorValue / (lengthFactorValue * lengthFactorValue)} MPa in Pa");

        }
    }
}
